[package]
name = "phishtest"
version = "0.1.0"
edition = "2024"

[dependencies]
#axum-reverse-proxy = "0.9"
axum = { version = "0.8" }
tokio = { version = "1", features = ["rt-multi-thread"] }
reqwest = { version = "0", features = ["cookies"] }
bytes = "1"
base64 = "0"
base32 = "0"
regex = "1.11.1"